### ISSUE TITLE
everbodys account switches

### ISSUE THREAD

**Issue by markedagain** [arkhitech/redmine_impersonate#4]
When i try to switch to a different user. everybody in my office started complaining saying they were also logged in as somebody else :(

**Comment by deltab** [comment]
If I'm reading init.rb correctly, the impersonated user is stored in the thread, and subsequent requests handled by the same thread inherit the impersonation.

The original User#current uses RequestStore: should this plugin do the same?

**Comment by qkdreyer** [comment]
https://github.com/cyrosy/redmine_impersonate

**Comment by hishammalik** [comment]
Now the plugin uses RequestStore.
